//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.16 at 07:20:06 ip. EEST 
//


package com.arstraffic.ftt.schemas.locationdata;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.arstraffic.ftt.schemas.locationdata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.arstraffic.ftt.schemas.locationdata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link com.arstraffic.ftt.schemas.locationdata.SiteType }
     * 
     */
    public SiteType createSiteType() {
        return new SiteType();
    }

    /**
     * Create an instance of {@link com.arstraffic.ftt.schemas.locationdata.LinkType.Distance }
     * 
     */
    public LinkType.Distance createLinkTypeDistance() {
        return new LinkType.Distance();
    }

    /**
     * Create an instance of {@link com.arstraffic.ftt.schemas.locationdata.LinkType }
     * 
     */
    public LinkType createLinkType() {
        return new LinkType();
    }

    /**
     * Create an instance of {@link com.arstraffic.ftt.schemas.locationdata.Jtdata.Linklist }
     * 
     */
    public Jtdata.Linklist createJtdataLinklist() {
        return new Jtdata.Linklist();
    }

    /**
     * Create an instance of {@link com.arstraffic.ftt.schemas.locationdata.Jtdata }
     * 
     */
    public Jtdata createJtdata() {
        return new Jtdata();
    }

    /**
     * Create an instance of {@link com.arstraffic.ftt.schemas.locationdata.Wgs84CoordinatesType }
     * 
     */
    public Wgs84CoordinatesType createWgs84CoordinatesType() {
        return new Wgs84CoordinatesType();
    }

    /**
     * Create an instance of {@link com.arstraffic.ftt.schemas.locationdata.ObstimeType }
     * 
     */
    public ObstimeType createObstimeType() {
        return new ObstimeType();
    }

    /**
     * Create an instance of {@link com.arstraffic.ftt.schemas.locationdata.SiteType.Name }
     * 
     */
    public SiteType.Name createSiteTypeName() {
        return new SiteType.Name();
    }

    /**
     * Create an instance of {@link com.arstraffic.ftt.schemas.locationdata.Jtdata.Sitelist }
     * 
     */
    public Jtdata.Sitelist createJtdataSitelist() {
        return new Jtdata.Sitelist();
    }

    /**
     * Create an instance of {@link com.arstraffic.ftt.schemas.locationdata.LinkType.Name }
     * 
     */
    public LinkType.Name createLinkTypeName() {
        return new LinkType.Name();
    }

    /**
     * Create an instance of {@link com.arstraffic.ftt.schemas.locationdata.Jtdata.Version }
     * 
     */
    public Jtdata.Version createJtdataVersion() {
        return new Jtdata.Version();
    }

}
