//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.16 at 07:20:06 ip. EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://FTT.arstraffic.com/schemas/LocationData/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.arstraffic.ftt.schemas.locationdata;
