package com.gofore.sujuvuus.schemas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2014-08-16T19:46:57.994+03:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
@WebService(targetNamespace = "http://www.gofore.com/sujuvuus/schemas", name = "TrafficFluencyPort")
@XmlSeeAlso({ObjectFactory.class})
public interface TrafficFluencyPort {

    @RequestWrapper(localName = "TrafficFluency", targetNamespace = "http://www.gofore.com/sujuvuus/schemas", className = "com.gofore.sujuvuus.schemas.TrafficFluency")
    @WebMethod(operationName = "TrafficFluency")
    @ResponseWrapper(localName = "TrafficFluencyResponse", targetNamespace = "http://www.gofore.com/sujuvuus/schemas", className = "com.gofore.sujuvuus.schemas.TrafficFluencyResponse")
    public void trafficFluency(
        @WebParam(mode = WebParam.Mode.OUT, name = "timestamp", targetNamespace = "http://www.gofore.com/sujuvuus/schemas")
        javax.xml.ws.Holder<ObstimeType> timestamp,
        @WebParam(mode = WebParam.Mode.OUT, name = "laststaticdataupdate", targetNamespace = "http://www.gofore.com/sujuvuus/schemas")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> laststaticdataupdate,
        @WebParam(mode = WebParam.Mode.OUT, name = "linkdynamicdata", targetNamespace = "http://www.gofore.com/sujuvuus/schemas")
        javax.xml.ws.Holder<TrafficFluencyResponse.Linkdynamicdata> linkdynamicdata
    );
}
